# Generated by Django 3.2 on 2023-04-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='ue_tipocontrato',
            field=models.IntegerField(blank=True, choices=[(1, 'Plazo Indefinido'), (2, 'Plazo Fijo'), (3, 'Plazo Indefinido 11 años o más'), (4, 'Trabajador de Casa Particular')], null=True, verbose_name='Tipo de contrato'),
        ),
    ]
